---
title: "functions-demo"
author: "Drew Radovich"
date: "2025-03-05"
html_document:
    theme: readable
    highlight: zenburn
    toc: true
params:
  url:
    value: x  
---



<br>
<hr>
<br>


### Example Report Assets Section 


```{r setup, include=TRUE}
knitr::opts_chunk$set( echo =T, message=F, warning=F )
```


```{r libraries}
# LOAD PACKAGES
library( dplyr )
library( pander )
library( knitr )
library( gender )

# SOURCE CUSTOM FUNCTIONS
source( "utils.R" )
```



```{r data}
# LOAD DATA
URL <- "https://raw.githubusercontent.com/Watts-College/paf-514-template/main/labs/batch-demo/asu-salaries-2020.csv"
d <- read.csv( URL )

# DATA STEPS 

d$first.name <- get_first_name( d$Full.Name )
d <- add_gender( d )
d <- add_titles( d )
d <- fix_salary( d )

d <-      # report sample
  d %>% 
  filter( title != "" & ! is.na(title) ) %>% 
  filter( Department.Description %in% academic.units )
```


<br>
<hr>
<br>





# Salary Range by Rank and Gender 

```{r, results="asis", fig.height=7, fig.width=10}
# {r, results="asis", fig.height=7, fig.width=10}
for( i in academic.units )
{
  
  d2 <- filter( d, Department.Description == i )
  if( nrow(d2) == 0 ) { next } 
  # create the salary summary by rank & gender table
  create_salaries_table()
  # create the top 5 salaries table 
  t.rank <-
    top_5_highest_paid(d2)
  # build the graph 
  t.salary <- 
  d2 %>% 
  group_by( title, gender ) %>% 
  summarize( q25=quantile(salary,0.25),
             q50=quantile(salary,0.50),
             q75=quantile(salary,0.75),
             n=n() ) %>% 
  ungroup() %>% 
  mutate( p= round( n/sum(n), 2) )

t.salary %>% build_graph( unit = i)


t.salary$q25 <- dollarize( t.salary$q25 )
t.salary$q50 <- dollarize( t.salary$q50 )
t.salary$q75 <- dollarize( t.salary$q75 )

t.salary %>% knitr::kable(format="html")
 
   # print the tables:  
  cat( paste('<h3>',"TOP FIVE SALARIES",'</h3>' ) )
  cat( t.rank %>% knitr::kable(format="html") )   

  cat( '<br><hr><br>' )
  
}

```
